[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
      \.git/
    | \.github/
    | docs/
    | resources/
    | scripts/
)
'''
[tool.mypy]
mypy_path = "./kiauh"
