[project]
requires-python = ">=3.8"

[project.optional-dependencies]
dev=["ruff"]

[tool.ruff]
required-version = ">=0.3.4"
respect-gitignore = true
exclude = [".git",".github", "./docs"]
line-length = 88
indent-width = 4
output-format = "full"

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"

